### ISSUE TITLE
conftest and page object for multiple pages

### ISSUE THREAD

**Issue by adiyosef** [AutomationPanda/tau-playwright-workshop#6]
great lecture!! i just started my new python-playwright project and wanted to know how would you handle a big project with multiple pages init, the conftest will be full of page inits fixtures, is there a way to handle it cleaner then that?

**Comment by AutomationPanda** [comment]
With pytest, you can actually have multiple `conftest.py` files. You can put a `conftest.py` in subdirectories to cover the tests in those directory paths. For example:

```
my-project
\- tests
   |- customers
   |  |- conftest.py
   |  \- test_customers.py
   |- payments
   |  |- conftest.py
   |  \- test_payments.py
   \- products
      |- conftest.py
      \- test_payments.py
```
